"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TableFactoryImpl_1 = require("./TableFactoryImpl");
var UserTable_1 = require("./UserTable");
var GroupTable_1 = require("./GroupTable");
var factoryimpl = new TableFactoryImpl_1.TableFactoryImpl();
var usertable = factoryimpl.createTable("UserTable");
console.log(usertable instanceof UserTable_1.UserTable);
console.log(usertable.rows);
var grouptable = factoryimpl.createTable("GroupTable");
console.log(grouptable instanceof GroupTable_1.GroupTable);
console.log(grouptable.rows);
